### ISSUE TITLE
根据文档做模型微调时执行脚本报错，batch_size = input.size(0) AttributeError: 'str' object has no attribute 'size'

### ISSUE THREAD

**Issue by EssinZhang** [FunAudioLLM/SenseVoice#134]
## ❓ Questions and Help
如题报错怎么解决？这里是报错片段
[2024-09-27 14:43:18,901][root][INFO] - rank: 0, dataloader start from step: 0, batch_num: 1, after: 1
Error executing job with overrides: ['++model=iic/SenseVoiceSmall', '++trust_remote_code=true', '++train_data_set_list=/home/yixin/myProject/senseVoice/data/train_test/train.jsonl', '++valid_data_set_list=/home/yixin/myProject/senseVoice/data/val_example.jsonl', '++dataset_conf.data_split_num=1', '++dataset_conf.batch_sampler=BatchSampler', '++dataset_conf.batch_size=6000', '++dataset_conf.sort_size=1024', '++dataset_conf.batch_type=token', '++dataset_conf.num_workers=4', '++train_conf.max_epoch=50', '++train_conf.log_interval=1', '++train_conf.resume=true', '++train_conf.validate_interval=2000', '++train_conf.save_checkpoint_interval=2000', '++train_conf.keep_nbest_models=20', '++train_conf.avg_nbest_model=10', '++train_conf.use_deepspeed=false', '++train_conf.deepspeed_config=/home/yixin/myProject/senseVoice/deepspeed_conf/ds_stage1.json', '++optim_conf.lr=0.0002', '++output_dir=./outputs']
Traceback (most recent call last):
  File "/home/yixin/myProject/FunASR/funasr/bin/train_ds.py", line 222, in <module>
    main_hydra()
  File "/home/yixin/anaconda3/envs/funasr/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/home/yixin/anaconda3/envs/funasr/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/home/yixin/anaconda3/envs/funasr/lib/python3.10/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/home/yixin/anaconda3/envs/funasr/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/home/yixin/anaconda3/envs/funasr/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/home/yixin/anaconda3/envs/funasr/lib/python3.10/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/home/yixin/anaconda3/envs/funasr/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/home/yixin/anaconda3/envs/funasr/lib/python3.10/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/home/yixin/anaconda3/envs/funasr/lib/python3.10/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/home/yixin/myProject/FunASR/funasr/bin/train_ds.py", line 56, in main_hydra
    main(**kwargs)
  File "/home/yixin/myProject/FunASR/funasr/bin/train_ds.py", line 195, in main
    trainer.validate_epoch(model=model, dataloader_val=dataloader_val, epoch=epoch + 1)
  File "/home/yixin/myProject/FunASR/funasr/train_utils/trainer_ds.py", line 750, in validate_epoch
    for batch_idx, batch in enumerate(dataloader_val):
  File "/home/yixin/anaconda3/envs/funasr/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 631, in __next__
    data = self._next_data()
  File "/home/yixin/anaconda3/envs/funasr/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "/home/yixin/anaconda3/envs/funasr/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 1372, in _process_data
    data.reraise()
  File "/home/yixin/anaconda3/envs/funasr/lib/python3.10/site-packages/torch/_utils.py", line 705, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/yixin/anaconda3/envs/funasr/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
  File "/home/yixin/anaconda3/envs/funasr/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yixin/anaconda3/envs/funasr/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yixin/myProject/FunASR/funasr/datasets/sense_voice_datasets/datasets.py", line 317, in __getitem__
    speech, speech_lengths = extract_fbank(
  File "/home/yixin/myProject/FunASR/funasr/utils/load_utils.py", line 173, in extract_fbank
    data, data_len = frontend(data, data_len, **kwargs)
  File "/home/yixin/anaconda3/envs/funasr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/yixin/anaconda3/envs/funasr/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yixin/myProject/FunASR/funasr/frontends/wav_frontend.py", line 125, in forward
    batch_size = input.size(0)
AttributeError: 'str' object has no attribute 'size'
. Did you mean: '_return_value'?
E0927 14:43:24.083000 140593130620736 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 0 (pid: 57488) of binary: /home/yixin/anaconda3/envs/funasr/bin/python
Traceback (most recent call last):
  File "/home/yixin/anaconda3/envs/funasr/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/yixin/anaconda3/envs/funasr/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/home/yixin/anaconda3/envs/funasr/lib/python3.10/site-packages/torch/distributed/run.py", line 879, in main
    run(args)
  File "/home/yixin/anaconda3/envs/funasr/lib/python3.10/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/home/yixin/anaconda3/envs/funasr/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/yixin/anaconda3/envs/funasr/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 263, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
/home/yixin/myProject/FunASR/funasr/bin/train_ds.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-09-27_14:43:24
  host      : zyxsLaptop.
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 57488)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

还有就是我明明有gpu 执行时我看参数device为啥是cpu？
![image](https://github.com/user-attachments/assets/b6daecd9-da29-412e-94a6-86e221ea3c44)

 - OS (e.g., Linux):   **WSL2 Ubuntu24.04**
 - FunASR Version (e.g., 1.0.0):  **1.1.8**
 - ModelScope Version (e.g., 1.11.0): 1.18.1
 - PyTorch Version (e.g., 2.0.0): 2.3.0
 - How you installed funasr (`pip`, source): source
 - Python version: 3.10.14
 - GPU (e.g., V100M32) RTX4060 laptop
 - CUDA/cuDNN version (e.g., cuda11.7): 12.1
 - Docker version (e.g., funasr-runtime-sdk-cpu-0.4.1) no
 - Any other relevant information:

**Comment by EssinZhang** [comment]
补充信息
![image](https://github.com/user-attachments/assets/72000c38-2f25-4500-acfa-6cda09c0fe8f)

**Comment by LauraGPT** [comment]
Check wav path
