### ISSUE TITLE
 ModuleNotFoundError: No module named 'typing_extensions'

### ISSUE THREAD

**Issue by daixun0913** [FunAudioLLM/SenseVoice#166]
Traceback (most recent call last):
  File "/home/pc/.local/bin/torchrun", line 5, in <module>
    from torch.distributed.run import main
  File "/home/pc/.local/lib/python3.10/site-packages/torch/__init__.py", line 1308, in <module>
    from .serialization import save, load
  File "/home/pc/.local/lib/python3.10/site-packages/torch/serialization.py", line 18, in <module>
    from typing_extensions import TypeAlias  # Python 3.10+
ModuleNotFoundError: No module named 'typing_extensions'

**Comment by daixun0913** [comment]
请问这是什么错，一直安不好
