### ISSUE TITLE
直接推理和funast推理都报错

### ISSUE THREAD

**Issue by huacilang** [FunAudioLLM/SenseVoice#23]
Traceback (most recent call last):
  File "/home/zhaoxy/whisper/code/SenseVoice/funasr_infer.py", line 8, in <module>
    model = AutoModel(model=model_dir,
  File "/opt/conda/lib/python3.10/site-packages/funasr/auto/auto_model.py", line 124, in __init__
    model, kwargs = self.build_model(**kwargs)
  File "/opt/conda/lib/python3.10/site-packages/funasr/auto/auto_model.py", line 192, in build_model
    tokenizer = tokenizer_class(**kwargs.get("tokenizer_conf", {}))
  File "/opt/conda/lib/python3.10/site-packages/funasr/tokenizer/sentencepiece_tokenizer.py", line 23, in __init__
    self._build_sentence_piece_processor()
  File "/opt/conda/lib/python3.10/site-packages/funasr/tokenizer/sentencepiece_tokenizer.py", line 32, in _build_sentence_piece_processor
    self.sp.load(self.bpemodel)
  File "/opt/conda/lib/python3.10/site-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/opt/conda/lib/python3.10/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())]

**Comment by LauraGPT** [comment]
update`sentencepiece`
