### ISSUE TITLE
训练时AttributeError: 'str' object has no attribute 'size'

### ISSUE THREAD

**Issue by badarrrr** [FunAudioLLM/SenseVoice#54]
Traceback (most recent call last):
  File "/gemini/code/FunASR/funasr/bin/train_ds.py", line 222, in <module>
    main_hydra()
  File "/root/miniconda3/lib/python3.9/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/root/miniconda3/lib/python3.9/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/root/miniconda3/lib/python3.9/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/root/miniconda3/lib/python3.9/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/root/miniconda3/lib/python3.9/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/root/miniconda3/lib/python3.9/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
  File "/root/miniconda3/lib/python3.9/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
  File "/root/miniconda3/lib/python3.9/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/root/miniconda3/lib/python3.9/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
  File "/gemini/code/FunASR/funasr/bin/train_ds.py", line 56, in main_hydra
    main(**kwargs)
  File "/gemini/code/FunASR/funasr/bin/train_ds.py", line 195, in main
    trainer.validate_epoch(model=model, dataloader_val=dataloader_val, epoch=epoch + 1)
  File "/root/miniconda3/lib/python3.9/site-packages/funasr/train_utils/trainer_ds.py", line 750, in validate_epoch
    for batch_idx, batch in enumerate(dataloader_val):
  File "/root/miniconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/root/miniconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
    return self._process_data(data)
  File "/root/miniconda3/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/root/miniconda3/lib/python3.9/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/root/miniconda3/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/miniconda3/lib/python3.9/site-packages/funasr/datasets/sense_voice_datasets/datasets.py", line 317, in __getitem__
    speech, speech_lengths = extract_fbank(
  File "/root/miniconda3/lib/python3.9/site-packages/funasr/utils/load_utils.py", line 173, in extract_fbank
    data, data_len = frontend(data, data_len, **kwargs)
  File "/root/miniconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/lib/python3.9/site-packages/funasr/frontends/wav_frontend.py", line 125, in forward
    batch_size = input.size(0)
AttributeError: 'str' object has no attribute 'size'

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1422) of binary: /root/miniconda3/bin/python
Traceback (most recent call last):
  File "/root/miniconda3/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/root/miniconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/root/miniconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/root/miniconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/gemini/code/FunASR/funasr/bin/train_ds.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-07-17_11:40:04
  host      : gjob-dev-468604710832730112-taskrole1-0
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1422)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

我把数据替换成funasr提供的那四个例子了，为什么训练会报这个问题呢？
![image](https://github.com/user-attachments/assets/178ea4d1-fe94-47ac-b628-50021ab98148)

**Comment by badarrrr** [comment]
我感觉是我的音频地址可能找不到，但是我没有专门的数据集，所以用的还是funasr给出的那几个音频地址

**Comment by sunbeibei-hub** [comment]
i meet this error!  do you settle it？
please, hellp me~

**Comment by sunbeibei-hub** [comment]
There is no problem with multiple GPU

**Comment by badarrrr** [comment]
I guess it is caused by the address from【source】.They didn't provide the .wav files which mentioned in the train_example.jsonl.
I change the .wav files source to the examples which are provided in the funasr project.You can check the funasr project finetune examples in https://github.com/modelscope/FunASR/blob/main/docs/tutorial/README.md
Or maybe you can download other .wav files directly and change the 【source】to absolute path.Hope it can help you!

**Comment by LauraGPT** [comment]
Please check your wav file.
